### PR TITLE
Exception message in json formatter

### LINKED ISSUE #957: JSON Formatter: Logs stack trace exception and should log cucumber assertions errors
Hi,

I think there is a bug in the 'json_formatter.js' at line 213, see snippet below:

        if (status === _status2.default.FAILED && exception) {
          data.result.error_message = exception.stack || exception;
        }

Any failed test will result in the stack trace being logged when IMO it should be the exception.message at a minimum and potentially the stack trace as well (it would be nice if you could turn on/off the stack trace errors).

Can someone confirm if this is a bug and how it will be resolved.

I am running NightwatchJS with CucumberJS, my environment details is as follows:

Node - v8.7.0
Cucumber - v3.03
Nightwatch - v0.9.16
Nightwatch cucumber - v8.2.2
Browser - Chrome v61.0.3163.100 
Chrome driver - v2.32
Selenium - v3.5.3
Os - Windows 7

I have attached a copy of json formatter output showing the error message at line 86

Regards,
Neville Humphrey

[chrome.cucumber.json.zip](https://github.com/cucumber/cucumber-js/files/1398538/chrome.cucumber.json.zip)

### PR DESCRIPTION
**Pull request by innocentiv**
Add exception.message to error_message if not already included in exception.stack

Fix #957

### CODE REVIEW

File: src/formatter/json_formatter.js [hunk 1]
```diff
@@ -156,7 +156,10 @@ export default class JsonFormatter extends Formatter {
         data.result.duration = testStep.result.duration
       }
       if (status === Status.FAILED && exception) {
-        data.result.error_message = exception.stack || exception
+        let message = exception.message || ''
+        let stack = exception.stack || ''
+        message = _.includes(stack, message) ? '' : message + '\n'
+        data.result.error_message = message + stack || exception
```
Comment (finaruioana) [inline src/formatter/json_formatter.js]: for consistency over the type of error_message, I would suggest to have a `JSON.stringify(exception)`. It would be a rare exception, but at least we know error_message will be a string all the time.

Comment (innocentiv) [reply src/formatter/json_formatter.js]: I omitted the JSON.stringify in the pull request because that would change the spec (JSON.stringify add escaped quotes to string object):

https://github.com/cucumber/cucumber-js/blob/267725e3a8b00e28336ef75727d7487e5a6739ab/src/formatter/json_formatter_spec.js#L128

https://github.com/cucumber/cucumber-js/blob/267725e3a8b00e28336ef75727d7487e5a6739ab/src/formatter/json_formatter_spec.js#L141

Adding a type check would enforce a string without changing the spec.
I wouldn't add more code if not really needed

```
data.result.error_message = message + stack || _.isString(exception) ? exception :  JSON.stringify(exception)
```

Comment (innocentiv) [reply src/formatter/json_formatter.js]: @finaruioana 

This may be a better solution, what do you think?


```javascript
if(_.isString(exception)) {
  data.result.error_message = exception
} else {
  let {message = '', stack = ''} = exception
  message = _.includes(stack, message) ? '' : message + '\n'
  data.result.error_message = message + stack || JSON.stringify(exception)
}
```

**Comment by innocentiv** [comment]
I have updated the pull request to force consistency over the type of error_message

**Comment by humphreyn** [comment]
Great work guys,
Sorry I couldn't be of more assistance. It's been mad at work and home:-)

File: src/formatter/json_formatter.js [hunk 2]
```diff
@@ -156,7 +156,14 @@ export default class JsonFormatter extends Formatter {
...
       }
       if (status === Status.FAILED && exception) {
-        data.result.error_message = exception.stack || exception
+        if (_.isString(exception)) {
+          data.result.error_message = exception
+        } else {
+          let { message = '', stack = '' } = exception
+          message = _.includes(stack, message) ? '' : message + '\n'
+          data.result.error_message =
+            message + stack || JSON.stringify(exception)
```
Comment (charlierudolph) [inline src/formatter/json_formatter.js]: This is hard for me to follow. Thoughts on breaking out a function `stringifyException` and focusing on making it easy to understand:
```js
function stringifyException(exception) {
  // if is string 
  //   return it
  // else if has message or stack
  //   if stack includes message
  //     return stack
  //   else 
  //     return message newline stack
  // else 
  //   return stringified exception
}
```
The function could then go in a util file and be unit tested with some sample exceptions from the different browsers and non-error objects

Comment (innocentiv) [reply src/formatter/json_formatter.js]: You are right, move this code to a function would be a better solution.
Any suggestion on where to put this utils file?
What about using /src/formatter/helpers/error_helpers.js?

Comment (charlierudolph) [reply src/formatter/json_formatter.js]: Sounds good to me

**Comment by innocentiv** [comment]
I have updated the pull request to add function stringifyException and unit test

File: src/formatter/json_formatter.js [hunk 3]
```diff
@@ -156,7 +161,7 @@ export default class JsonFormatter extends Formatter {
         data.result.duration = testStep.result.duration
       }
       if (status === Status.FAILED && exception) {
-        data.result.error_message = exception.stack || exception
+        data.result.error_message = stringifyException(exception)
```
Comment (charlierudolph) [inline src/formatter/json_formatter.js]: Thanks for the great test cases but thinking more on this feature I think we should use [node-assertion-error-formatter](https://github.com/charlierudolph/node-assertion-error-formatter) which is what we use when displaying errors in the terminal. It includes the logic for concatenating the message / stack and shows diffs as well. Sorry I didn't remember this sooner.

Comment (innocentiv) [reply src/formatter/json_formatter.js]: node-assertion-error-formatter does not pass 3 of the tests case I wrote. If those error are acceptable I can modify for the fourth time the pull request :)

 1) ErrorHelpers                                                                                     
      stringifyException                                                                             
        return stack:                                                                                                                                                                            
     AssertionError: expected '[object Object]stack' to equal 'stack'                                
                                                                                                     
 2) ErrorHelpers                                                                                     
      stringifyException                                                                             
        return message and stack:                                                                                                                                                   
     AssertionError: expected 'errorstack' to equal 'error\nstack'                                   
                                                                                                     
 3) ErrorHelpers                                                                                     
      stringifyException                                                                             
        stringify an object:                                                                         
    TypeError: stack.indexOf is not a function

Comment (charlierudolph) [reply src/formatter/json_formatter.js]: I just released v2.0.1 of `node-assertion-error-formatter` which should fix cases 2 and 3 (https://github.com/charlierudolph/node-assertion-error-formatter/commit/ca21cfd552ce090b0273bd160e44b7cb54f7c071). Please update the version in the package.json / yarn.lock. 

I think test case number 1 needs to be updated so the message is an empty string instead of undefined. Testing out the error constructor in node 8, this was always the case.

If all your test cases pass, I think the tests / util file you added can be deleted as the test cases are now covered in `node-assertion-error-formatter`. We can use `node-assertion-error-formatter` directly in `src/formatter/json_formatter.js`

**Comment by innocentiv** [comment]
I have updated the pull request. Now there is a small error when message is an empty string.

1) ErrorHelpers
       format
         return stack:
      AssertionError: expected '{"message":"","stack":"stack"}\nstack' to equal 'stack'

This is not a major error and should be fixed in assertion-error-formatter. I think we can merge this pull request and update later this dependency.

**Comment by aslakhellesoy** [comment]
Hi @innocentiv,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber
