### PR TITLE
Empty rerun file exits running no scenarios (#1302)

### LINKED ISSUE #1302: rerun reruns all tests if @rerun.txt is empty
If `@rerun.txt` exists and has not failing test in it (empty), it runs all features.

`cucumber-js @rerun.txt cucumber-js @rerun.txt`

If I had one failed test, it runs only the the specified test.

### PR DESCRIPTION
**Pull request by jshifflet**
Fixes #1302. 

Especially not sure about changes in ` src/cli/index.ts `.

Any suggestions for improvements would be greatly appreciated.

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Sorry for the late reply

We have added the PR to the Cucumber Open Board: https://github.com/orgs/cucumber/projects/8

We will review your solution soon

File: src/cli/configuration_builder.ts [hunk 1]
```diff
@@ -210,13 +210,13 @@ export default class ConfigurationBuilder {
...
           const content = await fs.readFile(filePath, 'utf8')
-          return _.chain(content).split('\n').map(_.trim).compact().value()
+          return _.chain(content).split('\n').map(_.trim).value()
         }
         return [arg]
       })
       const featurePaths = _.flatten(nestedFeaturePaths)
       if (featurePaths.length > 0) {
-        return featurePaths
+        return _.compact(featurePaths)
```
Comment (charlierudolph) [inline src/cli/configuration_builder.ts:219]: Can we please add a unit test for this change as well?

File: src/cli/index.ts [hunk 2]
```diff
@@ -181,6 +181,9 @@ export default class Cli {
       supportCodeLibrary,
     })
     await emitMetaMessage(eventBroadcaster)
+    if (configuration.featurePaths.length === 0) {
+      return { shouldExitImmediately: true, success: true }
+    }
```
Comment (charlierudolph) [inline src/cli/index.ts:186]: I disagree with this change. I think we run though the rest of things normally otherwise the formatters won't write that 0 scenarios / steps ran (and the user just gets no output)

**Comment by aurelien-reeves** [comment]
@charlierudolph thank you for the review 👍

@jshifflet sorry again for the delay 😰
Are you still interesting into working on that PR?

File: src/cli/index.ts (hunk 2 above)
Comment (jshifflet) [reply src/cli/index.ts:186]: Agreed.

I added the above snippet because removing caused the following timeout error:

```
 When I run cucumber-js with `@test.txt` # features/step_definitions/cli_steps.ts:19
       Error: function timed out, ensure the promise resolves within 10000 milliseconds
           at Timeout._onTimeout (/home/lemur/code/cucumber-js/src/user_code_runner.ts:80:18)
           at listOnTimeout (internal/timers.js:554:17)
           at processTimers (internal/timers.js:497:7)
```
If I set `pickleIds` to [] when `configuration.featurePaths.length === 0` things seem to work as expected without the unexpected side effect of no formatter output.

Are there other side effects to setting `pickleIds` to `[]` when there are no features to run, that I am not seeing?

**Comment by aurelien-reeves** [comment]
It looks pretty good to me.
@charlierudolph what do you think?

**Comment by aslakhellesoy** [comment]
@aurelien-reeves - the build isn't passing though, I haven't looked into why. Can you try to figure that out @aurelien-reeves ?

**Comment by aslakhellesoy** [comment]
Ok, it's passing now, after I merged in the `main` branch. The changelog needs to be updated. Otherwise LGTM

**Review by aurelien-reeves — COMMENTED** [review]
Oh, yes!

Please, update the changelog :)

**Review by davidjgoss — APPROVED** [review]

**Review by aurelien-reeves — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @jshifflet,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aurelien-reeves** [comment]
> 
> 
> @aurelien-reeves thanks for updating the changelog for me. Sorry about the delay.

It was not me, but I am sure that you are welcome 🙂 
I was about to do it indeed 😅
