### PR TITLE
typescript: fix types for hook functions so they can return 'skipped'

### LINKED ISSUE #1529: cannot skip a scenario anymore in v7
In V6, to skip a scenario, I used a Before each scenario hook

```ts
Before({ tags: '@ignore' }, async function () {
  return 'skipped';
});
```

This same code does not compile anymore in v7 with typescript:
```log
error TS2769: No overload matches this call.
  Overload 1 of 3, '(tags: string, code: TestCaseHookFunction): void', gave the following error.
    Argument of type '{ tags: string; }' is not assignable to parameter of type 'string'.
  Overload 2 of 3, '(options: IDefineTestCaseHookOptions, code: TestCaseHookFunction): void', gave the following error.
    Argument of type '(this: CustomWorld) => Promise<string>' is not assignable to parameter of type 'TestCaseHookFunction'.
      Type '(this: CustomWorld) => Promise<string>' is not assignable to type 'TestCaseHookFunctionWithoutParameter'.
        Type 'Promise<string>' is not assignable to type 'void | Promise<void>'.
          Type 'Promise<string>' is not assignable to type 'Promise<void>'.
```

What is the right way to skip a scenario in v7?

Thanks

### PR DESCRIPTION
**Pull request by davidjgoss**
Fixes #1529.

As part of this, added [tsd](√) so we can build up a representative set of TypeScript usages and make sure they don't regress.

### CODE REVIEW

File: src/support_code_library_builder/types.ts [hunk 1]
```diff
@@ -22,10 +22,10 @@ export interface ITestStepHookParameter {
   testStepId: string
 }
 
-export type TestCaseHookFunctionWithoutParameter = () => void | Promise<void>
+export type TestCaseHookFunctionWithoutParameter = () => any | Promise<any>
 export type TestCaseHookFunctionWithParameter = (
   arg: ITestCaseHookParameter
-) => void | Promise<void>
+) => any | Promise<any>
```
Comment (davidjgoss) [inline src/support_code_library_builder/types.ts:28]: `any` is obviously a bit broad but I think it's faithful to the API, in the sense that you _can_ return/resolve anything you want from a hook or step function, but `skipped` and `pending` have special meaning.

**Review by charlierudolph — APPROVED** [review]

**Comment by charlierudolph** [comment]
Very cool. Haven't seen a types test before
