### PR TITLE
Fix-1735 Parentheses in developers' paths break cucumber's own tests WIP

### LINKED ISSUE #1735: Cucumber's own features fail when parent directory contains parentheses
**Describe the bug**
Whenever the parent directory has parentheses in its name, I noticed the cucumber features tests start to fail. I also noticed that in the tests that are run, the path for the parent directory drops the parentheses from the path name. For the above reason, the path can not be found for a specified directory. 
```
22) Scenario:  # features/usage_json_formatter.feature:8
    ✔ Before # ../../Cucumber x/cucumber-js/src/support_code_library_builder/build_helpers.ts:13
    ✔ Given a file named "features/a.feature" with: # ../../Cucumber x/cucumber-js/src/support_code_library_builder/build_helpers.ts:13
        """
        Feature: a feature
          Scenario: a scenario
            Given step A
            And step A
            When step B
            Then step C
        """
    ✔ And a file named "features/step_definitions/steps.js" with: # ../../Cucumber x/cucumber-js/src/support_code_library_builder/build_helpers.ts:13
        """
        const {When} = require('@cucumber/cucumber')

        When('step A', function() {});
        When('step B', function() {});
        When('step C', function() {});
        When(/step D/, function() {});
        """
    ✔ When I run cucumber-js with `--format usage-json` # ../../Cucumber x/cucumber-js/src/support_code_library_builder/build_helpers.ts:13
    ✖ Then it outputs the usage data: # ../../Cucumber x/cucumber-js/src/support_code_library_builder/build_helpers.ts:13
        | PATTERN | PATTERN_TYPE       | URI                                | LINE | NUMBER OF MATCHES |
        | step A  | CucumberExpression | features/step_definitions/steps.js | 3    | 2                 |
        | step B  | CucumberExpression | features/step_definitions/steps.js | 4    | 1                 |
        | step C  | CucumberExpression | features/step_definitions/steps.js | 5    | 1                 |
        | step D  | RegularExpression  | features/step_definitions/steps.js | 6    | 0                 |
        AssertionError
            + expected - actual

            -13
            +3

            at /Users/emmanuelola/Documents/Cucumber (x)/cucumber-js/features/step_definitions/usage_json_steps.ts:15:30
            at Array.forEach (<anonymous>)
            at World.<anonymous> (/Users/emmanuelola/Documents/Cucumber (x)/cucumber-js/features/step_definitions/usage_json_steps.ts:9:18)
    ✔ After # ../../Cucumber x/cucumber-js/src/support_code_library_builder/build_helpers.ts:13
```

**To Reproduce**
1. Go to 'the root directory for the project'
2. Add a parent directory with a parentheses in its name (include some letters within the parentheses)
3. Open the project in your desired IDE
4. Run the tests
5. See error

**Expected behavior**
Passing tests

**Screenshots**
Untitled

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Version: Main Repository Branch

**Additional context**
Trying to run tests to contribute to cucumber-js with @mattwynne as part of the Cucumber first timers mob and the folder where I keep my code happens to have parentheses in its name. For more context, this is not the folder shown in the screenshot, that's simply provided for testing purposes.

### PR DESCRIPTION
**Pull request by eoola**
# Description

* Replaced stacktrace-js with stackChain
* Fixed line number mapping problem in stackChain using "@cspotcode/source-map-support"
* 2 tests still failing, intend to fix these before submitting PR

# Motivation & context

Tried to work with cucumber-js on my machine. The tests kept breaking since I had parentheses in my parent directory.

Fixes #1735 

## Type of change

- Refactoring/debt (improvement to code design or tooling without changing behaviour)
- Bug fix (non-breaking change which fixes an issue)

_Remember to add an entry to the relevant section of CHANGELOG.md as part of this pull request._

## Note to other contributors

None

## Update required of cucumber.io/docs

None

# Checklist:

- [x] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by eoola** [comment]
I've merged main into the branch. Let me know if there's anything else you'd like me to do.

**Comment by mattwynne** [comment]
Thanks @eoola that diff looks much easier to read now.

I notice the checks are failing at the `npm install` step - I wonder if, now that the merge is done, you need to run `npm install` again and check in / push the `package-lock.json` file. Can you give that a try?

**Comment by eoola** [comment]
I actually ran npm install before pushing because I noticed the package.json file was different.

**Comment by mattwynne** [comment]
That's better! Now we can see the test failures again.

File: src/support_code_library_builder/get_definition_line_and_uri_spec.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import assert from 'assert'
+import { getDefinitionLineAndUri } from './get_definition_line_and_uri'
+
+describe(getDefinitionLineAndUri.name, () => {
+  it('correctly gets the filename of the caller', () => {
+    const includeAnyFile = (): boolean => false
+    const { uri, line } = getDefinitionLineAndUri('.', includeAnyFile)
+    assert.strictEqual(
```
Comment (mattwynne) [inline src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: to fix the Windows failure, maybe we could try changing this to a regex match, something like:

    assert.ok(
      url.match(/^src.support_code_library_builder.get_definition_line_and_uri_spec\.ts$/)
    )

**Comment by mattwynne** [comment]
@charlierudolph @davidjgoss @aurelien-reeves I have a question about [this scenario](https://github.com/cucumber/cucumber-js/blob/main/features/custom_stack_trace.feature) which is the last one failing in this PR.

It looks to me like the scenario was intended to cover [this try/catch statement](https://github.com/cucumber/cucumber-js/blob/fec9841b92f903ad562a06274179d4a13a19e9df/src/support_code_library_builder/get_definition_line_and_uri.ts#L29) which no longer seems to be hit in this scenario. From what I can see, the user is now able to override `Error.prepareStackTrace` without it causing us any issues when we try to dig into stack traces ourselves. 🎉

I wonder if, now that we've moved away from using `stacktrace.js`, the whole thing is redundant?  I'm tempted to recommend we remove the try/catch statement (which would simplify this function a lot) and remove the scenario too.

What are your thoughts? Did I miss something?

**Comment by mattwynne** [comment]
@eoola we should remove the `.DS_Store` file from this PR.

I've just pushed a change to `main` to add it in `.gitignore` which should stop this from happening again, but I think you'll still need to `git rm .DS_Store` and then push another commit to your branch to remove it from the PR.

**Comment by mattwynne** [comment]
To get this to green (i.e. all the checks are passing) @eoola, we could remove [the assertion step](https://github.com/cucumber/cucumber-js/blob/main/features/custom_stack_trace.feature#L24-L27) from the failing scenario for now (oh, and [fix the Windows thing](https://github.com/cucumber/cucumber-js/pull/1824#discussion_r740464569)).

Getting the tests passing probably give us a better platform to have a discussion about what to do with that scenario.

Can you take care of those two changes?

File: src/support_code_library_builder/get_definition_line_and_uri_spec.ts (hunk 1 above)
Comment (davidjgoss) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: `path.normalize` may be able to help https://nodejs.org/api/path.html#pathnormalizepath

**Comment by davidjgoss** [comment]
@eoola thanks for sticking with this!

@mattwynne agree it seems particular to that library, no strong feelings about removing.

File: src/support_code_library_builder/get_definition_line_and_uri_spec.ts (hunk 1 above)
Comment (mattwynne) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: Ah yeah, that's a better idea. We should use it in the test, right? Because Windows users would expect see a path with forward-slashes when we actually surface the location of the step definition?

Comment (davidjgoss) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: Yep, use in the test.

> Because Windows users would expect see a path with forward-slashes when we actually surface the location of the step definition?

I don't think so - Windows users would, I think, expect to see stack traces with the OS-native delimiter (backslashes). That's what it's doing now, right? Hence your tests fails because your assert is forward slashes.

Comment (mattwynne) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: > I don't think so - Windows users would, I think, expect to see stack traces with the OS-native delimiter (backslashes)

Sorry! Sloppy language from me. I meant to say "backslashes" 🤦

Comment (eoola) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: what exactly would path.normalize resolve in this case and where would you like me to include that. Would you still like me to go ahead and replace the existing assertion with the one you provided?

**Comment by eoola** [comment]
> To get this to green (i.e. all the checks are passing) @eoola, we could remove [the assertion step](https://github.com/cucumber/cucumber-js/blob/main/features/custom_stack_trace.feature#L24-L27) from the failing scenario for now (oh, and [fix the Windows thing](https://github.com/cucumber/cucumber-js/pull/1824#discussion_r740464569)).
> 
> Getting the tests passing probably give us a better platform to have a discussion about what to do with that scenario.
> 
> Can you take care of those two changes?

Would you like me to remove the highlighted code from the actual test and push that?

File: src/support_code_library_builder/get_definition_line_and_uri_spec.ts (hunk 1 above)
Comment (mattwynne) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:8]: @eoola instead of doing what I suggested with the regex, I think if you use `path.normalize()` to process both the actual and expected values in the original assertion, that should mean we're comparing apples with apples, and this test should start to pass. Does that make sense? Can you give it a try?

**Comment by mattwynne** [comment]
> Would you like me to remove the highlighted code from the actual test and push that?

Yes, let's start with that.

File: src/support_code_library_builder/get_definition_line_and_uri_spec.ts (hunk 1 above)
Comment (eoola) [reply src/support_code_library_builder/get_definition_line_and_uri_spec.ts:9]: Done!

**Comment by aslakhellesoy** [comment]
Hi @eoola,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber
