### PR TITLE
grab own package version from regular require

### LINKED ISSUE #1439: Wrong version in meta message
The version number in the `meta` message is incorrect. Here is an example generated with 7.0.0-rc.0:

```
{"meta":{"protocolVersion":"13.1.0","implementation":{"name":"cucumber-js","version":"1.0.0"},"runtime":{"name":"node.js","version":"14.6.0"},"os":{"name":"darwin","version":"19.6.0"},"cpu":{"name":"x64"}}}
```

My hypothesis is that [readPkgUp](https://github.com/cucumber/cucumber-js/blob/3e0c21174fc86603f452106543912e52935e9341/src/cli/helpers.ts#L114) picks up a different `package.json` than our own.

### PR DESCRIPTION
**Pull request by davidjgoss**
Fixes #1439

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
I wonder if the new `import` causes the depth of the `lib` directory to change. I think it might work better with `JSON.parser(fs.readFileSync(...))`

**Comment by davidjgoss** [comment]
> I wonder if the new `import` causes the depth of the `lib` directory to change.

Yeah exactly that happened when doing `import pkg from "../../package.json"`, and this was fixed by switching to the `require` - the TypeScript compiler leaves those as they are and doesn't use them to calculate what it things the root should be.

The problem with the builds is a couple of ESLint rules failing, but I can't reproduce them locally, despite how my dependencies should be identical due to the lockfile. Would be good to know if you get the same or it's just me.

**Comment by davidjgoss** [comment]
Should be good to go now

File: features/support/hooks.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ Before(function (
   this.tmpDir = path.join(
     projectPath,
     'tmp',
-    `${path.basename(pickle.uri)}_${line.toString()}`
+    `${path.basename(pickle.uri) ?? ''}_${(line ?? '').toString()}`
```
Comment (charlierudolph) [inline features/support/hooks.ts:31]: What's the need for this change?

Comment (davidjgoss) [reply features/support/hooks.ts:31]: A new eslint rule that bubbled up

Comment (charlierudolph) [reply features/support/hooks.ts:31]: I don't understand how that is possible. If you revert this does the build fail?

Comment (aslakhellesoy) [reply features/support/hooks.ts:31]: We've recently upgraded the linter, which has new rules. Rules are only validated against modified files (that's how husky is set up).

So the linter only kicked in now that @davidjgoss modified the file.

Perhaps we should configure husky to lint/format everything? It will make commits a bit slower, but we avoid these kinds of surprised.

Comment (charlierudolph) [reply features/support/hooks.ts:31]: What is husky? Can you point me to the commit that introduced that? I personally prefer to lint everything each build and think linting modified files only is only useful if you are starting linting and don't want to fix everything at once (though there are also other ways of dealing with that too, ie disable the rules with errors and enable each separately when fixing them all)

Comment (aslakhellesoy) [reply features/support/hooks.ts:31]: Never mind my last comment - we're not using husky.

[Husky](https://github.com/typicode/husky) is a tool that runs arbitrary commands on git commit. It's popular for linting before commit.

Since we don't have this, what I think happened is:

* eslint was upgraded
* we don't enforce linting of all source code on commit
* a file that's not respecting the new eslint rules was updated
* the linter kicked in, forcing an unrelated change to be added just to keep the linter happy

Comment (davidjgoss) [reply features/support/hooks.ts:31]: AFAIK we lint all files new and old - previously had to fix some new errors to help dependabot do a eslint version bump for example. And the only change in this file is the one I made to fix the lint issue.

I can't quite figure out what has happened, but I wasn't getting the error locally, then saw it on Travis, then `rm -r`'d my `node_modules` and did a fresh yarn install, and then was able to see the error. This should be impossible because of lockfiles.

Comment (aslakhellesoy) [reply features/support/hooks.ts:31]: It's curious, but I don't think it's worthwhile spending more time understanding how this happened.

Is anything holding up merging this?

Comment (davidjgoss) [reply features/support/hooks.ts:31]: Agree could be a rabbit hole. FWIW I do think it's a bit of an over-the-top rule.

Comment (charlierudolph) [reply features/support/hooks.ts:31]: Can you please revert this change? I'd like to see the commit this error occur on CI? If it is still happening can we fix this in another PR? I'd like to narrow the discussion around it as I don't think both changes are needed

Comment (davidjgoss) [reply features/support/hooks.ts]: Reverted - and of course now it looks to be passing.

Here's [the build where it failed](https://travis-ci.org/github/cucumber/cucumber-js/builds/727824227) on this rule so I don't look totally mad.

**Comment by aslakhellesoy** [comment]
Thanks @davidjgoss - are we ready to merge?

**Comment by davidjgoss** [comment]
@aslakhellesoy yep
