### PR TITLE
fix(cli): allow targetting same file multiple times

### LINKED ISSUE #1706: CLI: Targetting the same file multiple times seems to duplicate the results
**Describe the bug**

In order to save time, I'm trying to use cucumber-js to target individual features and examples (a lot of them). I'm using these arguments:

```bash
$ npx cucumber-js "features/foo.feature:33" "features/foo.feature:34"
```

(to target 2 examples)

However, instead of saving time, it just takes more time. It seems that both examples are now executed twice.

**To Reproduce**

1. Follow the nodejs example: https://github.com/cucumber/cucumber-js/blob/main/docs/nodejs_example.md
2. Execute `npx cucumber-js features/simple_math.feature:19`, see:
    ```
    ...
    
    1 scenario (1 passed)
    3 steps (3 passed)
    ```
3. Same for line 20, `npx cucumber-js features/simple_math.feature:20`, see:
    ```
    ...
    
    1 scenario (1 passed)
    3 steps (3 passed)
    ```
4. Now, execute `npx cucumber-js features/simple_math.feature:19 features/simple_math.feature:20`, see:
    ```
    ............
    
    4 scenarios (4 passed)
    12 steps (12 passed)
    ```

**Expected behavior**

```
...
2 scenario (2 passed)
6 steps (6 passed)
```

**Desktop (please complete the following information):**
 - OS: Windows
- cucumberjs v7.3.0
- npm 6.14.11, node v12.21.0

**Smartphone (please complete the following information):**

### PR DESCRIPTION
**Pull request by nicojs**
Fix the issue where the same scenarios are executed multiple times when the feature file is targeted multiple times.

Example:

```shell
$ npx cucumber-js features/simple_math.feature:19 features/simple_math.feature:20
```

Will now result in:

```
...
2 scenario (2 passed)
6 steps (6 passed)
```

Fixes #1706

### CODE REVIEW

**Review by davidjgoss — APPROVED** [review]
Nice, thanks for doing this @nicojs!

File: src/cli/configuration_builder.ts [hunk 1]
```diff
@@ -143,6 +143,7 @@ export default class ConfigurationBuilder {
 
   async expandFeaturePaths(featurePaths: string[]): Promise<string[]> {
     featurePaths = featurePaths.map((p) => p.replace(/(:\d+)*$/g, '')) // Strip line numbers
+    featurePaths = [...new Set(featurePaths)] // Deduplicate the feature files; // Deduplicate the feature files
```
Comment (charlierudolph) [inline src/cli/configuration_builder.ts:146]: duplicate comment, second could be removed

**Comment by charlierudolph** [comment]
Looks great! Thanks for the fix

File: src/cli/configuration_builder.ts (hunk 1 above)
Comment (nicojs) [reply src/cli/configuration_builder.ts]: Oops. 😳

**Comment by nicojs** [comment]
I see you are using lodash here. Should `new Set` be changed to `_.unique`? Both work fine.

**Comment by aslakhellesoy** [comment]
Do we still need lodash @charlierudolph? Doesn’t the stdlib do everything it does now?

**Comment by charlierudolph** [comment]
Set is fine. I'll do an audit of what we use lodash for and see if we can remove it

**Comment by aslakhellesoy** [comment]
Hi @nicojs,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber
