### PR TITLE
fix return type of step hook function to allow async

### LINKED ISSUE #2037: BeforeStep and AfterStep hooks do not allow asynchronous functions - linting (es-lint) error
### 👓 What did you see?

The cucumber-js api reference for BeforeStep and AfterStep indicates that one can use async functions as the function parameter to BeforeStep and AfterStep, just like Before/After and BeforeAll/AfterAll ([API reference](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/api_reference.md)). However, when attempting to use an async function as an argument to AfterStep, I got the following typescript linting error:
`Promise returned in function argument where a void return was expected`

After doing some poking around, of the three hook types, the `TestStepHookFunction` type only allows for a return type of void, whereas the other two types, `TestStepHookFunction` and `TestStepFunction` have the following return types: `any | Promise<any>` ([code](https://github.com/cucumber/cucumber-js/blob/3928c673378ccabf2138b7c55873f6981e9eb134/src/support_code_library_builder/types.ts#L35)).

### ✅ What did you expect to see?

I expected that `TestStepHookFunction`, `TestStepHookFunction`, and `TestStepFunction` all had the return type of `any | Promise<any>`.

### 📦 Which tool/library version are you using?

Cucumber-js version: 7.3.2
Typescript version: 4.6.3
eslint: 8.12.0

### 🔬 How could we reproduce it?

1. Install cucumber-js version 7.3.2
2. Install and apply eslint version 8.12.0
3. Create a BeforeStep and pass in an async function, something like:
```
BeforeStep(async function(): Promise<void> {
await fetch("http://github.com");
})
```
4. Linter/compiler throws expected error: `Promise returned in function argument where a void return was expected`

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

### PR DESCRIPTION
**Pull request by davidjgoss**
### 🤔 What's changed?

Fix return type of step hook function to allow async, to be more accurate and prevent compile/lint errors for users.

### ⚡️ What's your motivation? 

Fixes #2037.

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

File: src/support_code_library_builder/types.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export type TestCaseHookFunction<WorldType> = (
 export type TestStepHookFunction<WorldType> = (
   this: WorldType,
   arg: ITestStepHookParameter
-) => void
+) => any | Promise<any>
```
Comment (mattwynne) [inline src/support_code_library_builder/types.ts:38]: `any` implies we expect an interesting return value. Do we look at the return value of a hook? If not, I suggest `void | Promise<void>` is better.

File: test-d/hooks.ts [hunk 2]
```diff
@@ -17,6 +17,14 @@ After(function () {})
 BeforeStep(function () {})
 AfterStep(function () {})
 
+// should allow hook functions to be async
+BeforeAll(async function () {})
```
Comment (mattwynne) [inline test-d/hooks.ts:21]: Did you not want to use our own types here for these functions?

e.g. for `BeforeStep` and `AfterStep` could we not use the `TestStepHookFunction` from above? Or am I missing something?

Comment (davidjgoss) [reply test-d/hooks.ts:21]: That type is implicitly being used - the goal with this test is to write what a user would typically write and make sure it passes the type check.

File: src/support_code_library_builder/types.ts (hunk 1 above)
Comment (davidjgoss) [reply src/support_code_library_builder/types.ts:38]: Good question.

It's not explicitly documented (per https://github.com/cucumber/cucumber-js/issues/1312#issuecomment-1016807156 which we need to address) but the return value can be "skipped" or "pending" as with regular steps.

It would be good to add this explicitly to the typings but I'm wary of suddenly causing compilation issues for people that e.g. are using chain promises and implicitly returning the result.

I'll do a little experimenting.

Comment (aurelien-reeves) [reply src/support_code_library_builder/types.ts:38]: `string | void | Promise<string | void>` won't work?

Comment (davidjgoss) [reply src/support_code_library_builder/types.ts:38]: (It doesn't really make sense to `return 'pending'` from a `BeforeStep`, so we should reconsider that, which I think was just an accident of the implementation.)

Comment (davidjgoss) [reply src/support_code_library_builder/types.ts:38]: > `string | void | Promise<string | void>` won't work?

My thought was around user code like:

```
BeforeStep(() => {
  return somethingAsyncThatReturnsPromise()
})
```

Where they are returning the promise so cucumber awaits it, but it resolves to some value that isn't a string so it fails the compilation, and now they have to refactor. Maybe less relevant now with `async/await` being so prevalent though.

Comment (davidjgoss) [reply src/support_code_library_builder/types.ts:38]: > We may use `any` in a first time, implementing a deprecation notice when not being an expected return type, then fix it in a version after that?

Yeah that sounds like a good plan. We need to rationalise this, plus the return types for the other hooks and steps, which I think should happen in a major release.

Comment (mattwynne) [reply src/support_code_library_builder/types.ts:38]: Just FYI, you can use a concrete string value as a type in Typescript, so it could be `"skipped" | "pending" | void` which is narrower than `string | void`.

I see your point about keeping it loose though David, consider also people this:

`BeforeStep(somethingAsyncThatReturnsPromise)`

File: test-d/hooks.ts (hunk 2 above)
Comment (mattwynne) [reply test-d/hooks.ts:21]: 💡  thanks for clarifying!

File: src/support_code_library_builder/types.ts (hunk 1 above)
Comment (davidjgoss) [reply src/support_code_library_builder/types.ts:38]: Yep another good example.

What do we think then to merging this and raising something new to fix all these types properly for 9.0.0?

Comment (mattwynne) [reply src/support_code_library_builder/types.ts:38]: Good plan. 👍

Comment (davidjgoss) [reply src/support_code_library_builder/types.ts:38]: New issue here https://github.com/cucumber/cucumber-js/issues/2040
