### PR TITLE
Fix #1621: Json formatter fails with tagged examples

### LINKED ISSUE #1621: Cucumber JSON report fails to generate when a scenario outline has a tag
Cucumber Version: 7.0.0
Node Version: 14.15.0
Operating System: MacOS Big Sur v11.2.1

Given this following test case:
```
@parent_tag
Scenario Outline: Sample test case
Given this is a test case
When I have the following data table
| <scenario_example> |
Then a JSON report will be generated

@child_tag_1
Examples:
| scenario_example |
| Test Child Tag 1 |

@child_tag_2
Examples:
| scenario_example |
| Test Child Tag 2 |
```

When I run the test case above with the tag: "--tags @child_tag_2" and "-f json:reports/cucumber-report.json", the test case runs successfully, but upon generating an report, the following error occurs:
```
TypeError: Cannot read property 'location' of undefined
    at /Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:185:34
    at arrayMap (/Users/project-folder/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Users/project-folder/node_modules/lodash/lodash.js:9622:14)
    at JsonFormatter.getScenarioTags (/Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:180:33)
    at JsonFormatter.getScenarioData (/Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:125:24)
    at /Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:84:29
    at Array.map (<anonymous>)
    at /Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:69:36
    at /Users/project-folder/node_modules/lodash/lodash.js:3585:27
    at /Users/project-folder/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/Users/project-folder/node_modules/lodash/lodash.js:3032:24)
    at /Users/project-folder/node_modules/lodash/lodash.js:4936:18
    at baseMap (/Users/project-folder/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/Users/project-folder/node_modules/lodash/lodash.js:9622:14)
    at JsonFormatter.onTestRunFinished (/Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:63:43)
    at EventEmitter.<anonymous> (/Users/project-folder/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:23:22)
```

Therefore I can't generate any JSON report.

I tried removing the scenario outline example tags and it proceeded with generating the JSON report.

### PR DESCRIPTION
**Pull request by aurelien-reeves**
Fixes #1621

- [x] Add tests
- [x] Make tests pass
- [x] Refactor
- [x] Document (update CHANGELOG)

### CODE REVIEW

File: src/formatter/json_formatter.ts [hunk 1]
```diff
@@ -317,20 +318,33 @@ export default class JsonFormatter extends Formatter {
...
-    })
+    const scenario = gherkinScenarioMap[pickle.astNodeIds[0]]
+
+    const asJsonTag = (tagData: IPickleTag): IJsonTag =>
+      this.getScenarioTag(tagData, feature, scenario)
+
+    return pickle.tags.map(asJsonTag)
+  }
+
+  getScenarioTag(
```
Comment (davidjgoss) [inline src/formatter/json_formatter.ts:329]: Could this method be private?

File: src/formatter/json_formatter.ts [hunk 2]
```diff
@@ -317,20 +318,33 @@ export default class JsonFormatter extends Formatter {
...
-        ? featureSource.location.line
-        : scenarioSource.location.line
-      return {
-        name: tagData.name,
-        line,
-      }
-    })
+    const scenario = gherkinScenarioMap[pickle.astNodeIds[0]]
+
+    const asJsonTag = (tagData: IPickleTag): IJsonTag =>
```
Comment (davidjgoss) [inline src/formatter/json_formatter.ts:323]: Consider inlining this function in the `map` for better readability

File: features/scenario_outlines.feature [hunk 3]
```diff
@@ -93,3 +93,26 @@ Feature: Scenario Outlines and Examples
...
     And it runs 4 scenarios
+
+  Scenario: scenario outlines with tagged examples
+    Given a file named "features/scenario_outline.feature" with:
+      """
+      Feature: a feature
+        Scenario Outline: a scenario
+          Given a step <id>
+
+        @tag
```
Comment (davidjgoss) [inline features/scenario_outlines.feature:104]: Would it be worth testing the multiple examples tables with different tags here?

**Review by davidjgoss — COMMENTED** [review]
Looks good, couple of queries, and I think we still need a changelog entry.

**Comment by aurelien-reeves** [comment]
> 
> 
> Looks good, couple of queries, and I think we still need a changelog entry.

I've pushed an update to the changelog.
The PR has not been updated yet, but the branch is https://github.com/cucumber/cucumber-js/commits/fix-1621-json-formatter-tagged-examples

File: src/formatter/json_formatter.ts (hunk 1 above)
Comment (aurelien-reeves) [reply src/formatter/json_formatter.ts:329]: Yes, it could.
Why other methods in that class are not private?

File: src/formatter/json_formatter.ts (hunk 2 above)
Comment (aurelien-reeves) [reply src/formatter/json_formatter.ts:323]: Actually I did it that way for readability
But maybe it is unsuccessful 😅

File: features/scenario_outlines.feature (hunk 3 above)
Comment (aurelien-reeves) [reply features/scenario_outlines.feature:104]: Yes, I'll do that.
We could even add two example tables with more tags to cover even more possibilities!?

File: src/formatter/json_formatter.ts (hunk 2 above)
Comment (davidjgoss) [reply src/formatter/json_formatter.ts:323]: Most of the time array fns like `map` and `filter` tend to be inline (at least in JS land). Subjective though, not super fussed about it.

File: src/formatter/json_formatter.ts (hunk 1 above)
Comment (davidjgoss) [reply src/formatter/json_formatter.ts:329]: Good question!

I guess technically the class could be extended by a user for their own formatter, though I'm not sure why anyone would extend this one.

File: features/scenario_outlines.feature (hunk 3 above)
Comment (davidjgoss) [reply features/scenario_outlines.feature:104]: I think two scenarios - one with the simplest, one with the most complex permutation you mentioned - should be good.

**Comment by davidjgoss** [comment]
> I've pushed an update to the changelog...The PR has not been updated yet

Really confused about how/why this commit doesn't show up on the PR - is there a trick I don't know? :)

**Comment by aurelien-reeves** [comment]
I'll update the PR with your remarks at the latest on monday

Thanks for your review :)

**Review by davidjgoss — APPROVED** [review]
